repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [--statistics, "--ignore=F401,F403,E501,E502"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        verbose: true
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies:
          - types-requests==2.28.11.12
          - types-tqdm==4.64.7.12
