name: Test

on:
  [ push, pull_request ]

jobs:
  test:
    name: Run tests with pytest
    container: yuigawada/jaspice
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Init
        run: python3 -m pip uninstall -y jaspice
      - name: Install pytest
        run: |
          python3 -m pip install pytest pytest-cov
      - name: Add path for Python packages
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt
      - name: Run tests
        run: python3 -m pytest --cov=jaspice --cov-branch --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          root_dir: true
          name: codecov-umbrella
          verbose: true
